// <auto-generated />
using System;
using Graph.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Graph.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230209144148_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Graph.Models.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ce4a057-576c-4ecf-81f2-c786de651b37"),
                            Name = "Intellect.",
                            SuperheroId = new Guid("1f6e4477-84d9-4d82-8860-d2ce3a0e2956")
                        },
                        new
                        {
                            Id = new Guid("2c7e0d51-5604-4628-8f8c-7b03b271e34b"),
                            Name = "Fighting",
                            SuperheroId = new Guid("1f6e4477-84d9-4d82-8860-d2ce3a0e2956")
                        },
                        new
                        {
                            Id = new Guid("8c813a1b-e026-4c95-96ce-8ecc0b4a8c6e"),
                            Name = "Wealth.",
                            SuperheroId = new Guid("1f6e4477-84d9-4d82-8860-d2ce3a0e2956")
                        },
                        new
                        {
                            Id = new Guid("39369814-f8a0-4131-b691-136df41e197a"),
                            Name = "Deflect blaster power.",
                            SuperheroId = new Guid("61f2d09d-cb5f-4084-8773-f14140ec0466")
                        },
                        new
                        {
                            Id = new Guid("dce986e6-2361-4765-8400-e998b96275d4"),
                            Name = "Espionage",
                            SuperheroId = new Guid("c98e94b0-2729-4bbd-b450-bd7c21092906")
                        },
                        new
                        {
                            Id = new Guid("2a5040d5-0221-4141-86ff-8bae61bd38c5"),
                            Name = "Infiltration",
                            SuperheroId = new Guid("c98e94b0-2729-4bbd-b450-bd7c21092906")
                        },
                        new
                        {
                            Id = new Guid("8ea56a05-c379-417c-8a84-99d7b354efc9"),
                            Name = "Subterfuge",
                            SuperheroId = new Guid("c98e94b0-2729-4bbd-b450-bd7c21092906")
                        });
                });

            modelBuilder.Entity("Graph.Models.Superhero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f6e4477-84d9-4d82-8860-d2ce3a0e2956"),
                            Age = 32,
                            Description = "Batman was originally introduced as a ruthless vigilante who frequently killed or maimed criminals, but evolved into a character with a stringent moral code and strong sense of justice. Unlike most superheroes, Batman does not possess any superpowers, instead relying on his intellect, fighting skills, and wealth.",
                            Name = "Batman"
                        },
                        new
                        {
                            Id = new Guid("61f2d09d-cb5f-4084-8773-f14140ec0466"),
                            Age = 21,
                            Description = "Luke Skywalker was a Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known. Along with his friends Princess Leia and Han Solo, Luke battled the evil Empire, discovered the truth of his parentage, and ended the tyranny of the Sith.",
                            Name = "Luke Skywalker"
                        },
                        new
                        {
                            Id = new Guid("c98e94b0-2729-4bbd-b450-bd7c21092906"),
                            Age = 26,
                            Description = "Black Widow, real name Natasha Romanoff, is a trained female secret agent and superhero that appears in Marvel Comics. Associated with the superhero teams S.H.I.E.L.D. and the Avengers, Black Widow makes up for her lack of superpowers with world class training as an athlete, acrobat, and expert martial artist and weapon specialist.",
                            Name = "Black Widow"
                        });
                });

            modelBuilder.Entity("Graph.Models.Ability", b =>
                {
                    b.HasOne("Graph.Models.Superhero", "Superhero")
                        .WithMany("Abilities")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("Graph.Models.Superhero", b =>
                {
                    b.Navigation("Abilities");
                });
#pragma warning restore 612, 618
        }
    }
}
